name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23libV11IIzk0kOjG5"
GITHUB_OWNER = "sanguine886"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://browse.sanguine.qzz.io/api/auth"
NEXT_PUBLIC_API_URL="https://browse.sanguine.qzz.io"

